PREFIX:= a

DamMet: deammeth.cc myargparser.cc ${PREFIX}/lib/libnlopt.a
	$(CXX) -O2  deammeth.cc myargparser.cc ${PREFIX}/lib/libnlopt.a -std=c++11 -I ${PREFIX}/include -L ${PREFIX}/lib -lhts -lz -lm -lbz2 -llzma -o DamMet -lpthread 

.PHONY: install clean

install: DamMet
	mkdir -p ${PREFIX}/bin
	cp DamMet ${PREFIX}/bin

clean:
	rm -f DamMet
