PREFIX:= abc

DamMet: deammeth.cc myargparser.cc ${PREFIX}/lib/libnlopt.a
	g++  -O2  deammeth.cc myargparser.cc ${PREFIX}/lib/libnlopt.a -std=c++11 -I ${PREFIX}/include  -lhts -lz -lm -lbz2 -llzma -o DamMet -lpthread 

.PHONY: install clean

install: DamMet
	mkdir -p ${PREFIX}/bin
	cp DamMet ${PREFIX}/bin

clean:
	rm -f DamMet
